spring:
  application:
    name: factura-service-sp
  profiles:
    active: test
  config:
    import: "optional:configserver:http://config-server:8888"
    #import: "optional:configserver:http://localhost:8888"